---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pks-rancher-reg
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pks-rancher-reg
subjects:
  - kind: ServiceAccount
    name: pks-rancher-reg
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: pks-rancher-reg
type: Opaque
data:
  rancherserver: cmFuY2hlci56b2xsZXIuY29tCg==
  rancherbearer: dG9rZW4tdjhjeGY6a2R3OHQ4NHJtbDc2OXA2OG01cWpxZmNwMm5jaHp3cW5iNWhjcnZmcHZta3hzdmx4ZmJ6a2Z4
  rancherca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQWRhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFvTVJJd0VBWURWUVFLRXdsMGFHVXRjbUZ1WTJneEVqQVFCZ05WQkFNVENXTmhkSFJzWlMxallUQWVGdzB4T1RBM01USXhOekUzTlRsYUZ3MHlPVEEzTURreE56RTNOVGxhTUNneEVqQVFCZ05WQkFvVENYUm9aUzF5WVc1amFERVNNQkFHQTFVRUF4TUpZMkYwZEd4bExXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVKaUlzenduQVFENDRHb0E5ZjNINjBaZnpjUUJURTFaazllbU1QNDdpSnA2Zk9YRzNLekpSZklqajZpM05OVDh2MDBUQThMOWZCMTVGMEFvUHVISUhpQnpwRjV0MHdtRjJ4SEVhRldYUmQ3cmVrYkZXcmMweGJETERqc0dGc2drNmdEa0hNcG9oLzZSRmh4bzJVdGdPcjlCdm1EamgwNjBhanN3OUp4K1VrMUlUTG1KU3lNRzdqWVkwM3RtZVJRaTNHc3BsOU9NMkZvSlRwQTJIVWxzY2g0MnNUcWh6M0o1dUlTSWgyQlZpTlhDaGViS0hGOGU1SGNmOUhGaHdTOWVCN2x4M3JmZyt5L1N5UXUyVzNvVmtGOTNtdDlBQ3hiUVZNa3EvT05vN2M1ZTV1QmIrdU5XdEJrdWgvMFhMMy9Iendzd2htVU5KcWlmaG1ENGZ3Y3A2UUlEQVFBQm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJVENZOVJySFdzY2MvVkJPR09sNjdaN3Q1L1pjQ2lNU05FS0ZWM1IyYUpZaU9XRlBGazU5SHN1QjVOamNYV016TnZwTUNRTmZrY3p5dmRuZC9pc04xNUR2SmlUQVN6ZC9nc2tUU282d0tLcFRTaVAwUHIzVVBvUlNCa3F4T0U1VW5IMTlSTXh1STFIVjNpN29iN1dWSVBSR1RCUWEydVpUSVVvUlNCYkZHQnVRYWNIUytTT1RXa1JCUWdXMFlyWVN6ZVo3bFBiQTZBUWhXL0dwdlZ2MWJEZzNmQ3E0dTdhcDRHVnZQOFZ6VGt3WDRmTTF3SFVXdmw1Y1VuRS9VODNBellQZjVaSEhkMGxGSEk2TE5Da09PL1dxN3FublFvZzVjR3pYZHR3WDdBaUtWbXhNbENpTlJMdmhYY3JsVDl2MysyNkNrMFpWc2FMdnJVTVFHTjZUYXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pks-rancher-reg
spec:
  template:
    spec:
      initContainers:
      - name: pks-rancher-reg
        image: harbor2.zoller.com/library/pks-rancher-reg:latest
        command: ["/pks-rancher-reg.sh"]
        env:
        - name: RANCHER_SERVER
          valueFrom:
            secretKeyRef:
              name: pks-rancher-reg
              key: rancherserver
        - name: RANCHER_BEARER
          valueFrom:
            secretKeyRef:
              name: pks-rancher-reg
              key: rancherbearer
        - name: CURL_CA_BUNDLE
          value: /tmp/rancherca
        volumeMounts:
          - name: rancherca
            mountPath: /tmp/
            readOnly: true
      volumes:
        - name: rancherca
          secret:
            secretName: pks-rancher-reg
      containers:
        - name: pks-ranger-reg-cleanup
          image: harbor2.zoller.com/library/pks-rancher-reg:latest
          command: ["/kubectl", "delete", "secrets/pks-rancher-reg"]
      restartPolicy: Never
      serviceAccountName: pks-rancher-reg
